version: "2.0"
services:
  vsftpd:
    image: alpine-vsftpd
    build: .
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ~/docker/vsftpd-data/:/home/ftp/:rw
      - ~/docker/vsftpd-data/log/:/var/log/vsftpd/:rw
    environment:
      - FTP_USER=admin
      - FTP_PASS=notneedhere
      - PASV_ADDRESS=172.26.180.129
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
